version: '3'
services:
  app:
    build: .
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/softdesign?user=root&password=secret
    restart: always
    links:
      - mysql:mysql
    networks:
      - mysql-compose-network
    ports:
      - 8080:8080
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: softdesign
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge